name: dmt_expedia
channels:
  - conda-forge
  #- defaults

dependencies:
  - python>=3.9
  - jupyterlab
  - notebook
  - ipywidgets
  - tqdm
  # - pyarrow # for fast serialization
  # Core scientific python
  - numpy
  - pandas
  - scipy
  # Plotting
  - matplotlib
  - seaborn
  # ML
  - scikit-learn
  - lightgbm
  - shap # for feature importance
  # Example of how to add pip dependencies
#  - pip=21.2.4
#  - pip:
#    - torchmetrics==0.9.0